name: Block Direct Push to Main
on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack Message
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "🚨 **${{ github.actor }}가 ${{ github.repository }} 프로젝트의 Main Branch로 푸시를 시도했습니다!**",
              "attachments": [
                {
                  "color": "#ff0000",
                  "fields": [
                    {
                      "title": "Pusher",
                      "value": "${{ github.actor }}",
                      "short": true
                    },
                    {
                      "title": "Commit Message",
                      "value": "${{ github.event.head_commit.message }}",
                      "short": false
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
